### ISSUE TITLE
Cache the public keys once generated

### ISSUE THREAD

**Issue by fousa** [icapps/ios-cara#11]
The public keys are generated for the domain on every request. but I think we should cache the generated value so that the public key pinning process is optimised.

**Comment by dgyesbreghs** [comment]
We never know when they're going to update the certificates. So there is going to be a 'grey periode'. For example: when someone has stolen the private 🔑
Don't think this will improve the security/performance. Maybe I'm wrong 🤔

**Comment by fousa** [comment]
Good point. 

I was only planning to cache it in memory, I think Alamofire does the same but I'm not 100% sure. Not sure if calculating the public key on every request is a performance issue neither. To be examined.
