### ISSUE TITLE
Support Codable types in request body

### ISSUE THREAD

**Issue by wvteijlingen** [icapps/ios-cara#49]
Currently Cara supports two types for the body parameter: `Data` and any Foundation type that can be serialised using `JSONSerialization`.

It would be nice if it would also support a third type: `Codable`. That would allow us to use any type that implements the `Codable` protocol as the body.

Currently we are working around this by manually encoding to `Data` and then using that in the body, but that makes error handling cumbersome and is error prone to do every time.

**Comment by icappsCedric** [comment]
Done in master
